name: Terraform Prod Apply for Db Resources
on:
  workflow_dispatch:

jobs:
  Terraform-Action:
    runs-on: AGENT

    env:
      environment: PROD
      folder: db
      backendrg: "rg-org-prod-eus-tf"
      backendstorageaccount: "storgprodeustf01"
      backendcontainer: "org-prod-terraform-statefile"

    defaults:
      run:
        working-directory: "./terraform/env/prod/db"

    steps:
      #==================================================
      # Checkout Code Repository
      #==================================================   
      - name: 'Checkout Code Repository'
        uses: actions/checkout@v2

      #==================================================
      # Set Environment Variables to PROD                       
      #==================================================   
      - name: Use PROD Environment Variables
        run: |
          set +x
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZ_SUB_ID_org_PROD }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZ_TEN_ID_org_PROD }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ secrets.AZ_CLI_ID_org_PROD }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.AZ_CLI_SEC_org_PROD }}" >> $GITHUB_ENV
          set -x
      #==================================================
      # Terraform Init with backend   
      #==================================================
      - name: Terraform Init with backend
        id: init
        run: terraform init -backend-config="resource_group_name=$backendrg" -backend-config="storage_account_name=$backendstorageaccount" -backend-config="container_name=$backendcontainer" -backend-config="key=$environment.$folder.terraform.tfstate"

      #==================================================
      # Terraform plan                   
      #==================================================
      - name: Terraform plan
        id: plan
        run: |
          terraform plan -var-file="terraform.tfvars" --out tfplan.binary
          terraform show -json tfplan.binary > tfplan.json

      #==================================================
      # Checkov Analysis                    
      #==================================================
      - name: Checkov Analysis
        id: checkov
        run: checkov -f tfplan.json --soft-fail

      #==================================================
      # Terraform apply                   
      #==================================================
      - name: Terraform apply
        id: apply
        run:  terraform apply --auto-approve